version: '2'
networks:
  default:
    external: true
    name: main
services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports: []
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
      - "10.56.4.2:5432:5432"
    volumes:
      - /srv/postgres-data/data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 1g
    environment:
      POSTGRES_PASSWORD: postgres